# Generated by Django 5.2.17 on 2026-09-29 19:36

import core_banking.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.CharField(default=core_banking.models.generate_account_id, max_length=64, primary_key=True, serialize=False)),
                ('account_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('routing_number', models.CharField(default='021000089', max_length=16)),
                ('swift_bic', models.CharField(default='AEGSHZUS33', max_length=16)),
                ('account_holder_name', models.CharField(db_index=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_holder_email', models.EmailField(max_length=254)),
                ('account_holder_phone', models.CharField(max_length=32)),
                ('account_type', models.CharField(choices=[('checking', 'Standard Checking'), ('savings', 'High-Yield Savings'), ('business_checking', 'Commercial Operating Checking'), ('money_market', 'Money Market Account'), ('treasury_escrow', 'Treasury Escrow Account')], default='checking', max_length=32)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('CAD', 'Canadian Dollar (CA$)')], default='USD', max_length=8)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('hold_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('overdraft_limit', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=18)),
                ('status', models.CharField(choices=[('active', 'Active & Unrestricted'), ('frozen', 'Compliance Frozen'), ('dormant', 'Dormant'), ('restricted', 'Administrative Restrictions')], default='active', max_length=16)),
                ('kyc_tier', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('opened_date', models.DateField(default=django.utils.timezone.now)),
                ('branch_code', models.CharField(default='NYC-01', max_length=16)),
                ('interest_rate_annual', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['-balance'],
            },
        ),
        migrations.CreateModel(
            name='BranchVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(default='Downtown Flagship NYC-01', max_length=255)),
                ('branch_code', models.CharField(default='NYC-01', max_length=16, unique=True)),
                ('vault_cash_usd', models.DecimalField(decimal_places=2, default=Decimal('14250000.00'), max_digits=18)),
                ('teller_drawers_cash_usd', models.DecimalField(decimal_places=2, default=Decimal('485000.00'), max_digits=18)),
                ('reserve_requirement_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=5)),
                ('central_bank_deposit_usd', models.DecimalField(decimal_places=2, default=Decimal('28500000.00'), max_digits=18)),
                ('last_audited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('daily_eod_reconciled', models.BooleanField(default=True)),
                ('auditor_name', models.CharField(default='Arthur Kensington (Chief Auditor)', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=8)),
                ('rate_to_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('buy_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sell_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('change_24h', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.CharField(default=core_banking.models.generate_card_id, max_length=64, primary_key=True, serialize=False)),
                ('cardholder_name', models.CharField(max_length=255)),
                ('card_number_masked', models.CharField(max_length=32)),
                ('full_card_number_virtual', models.CharField(max_length=32)),
                ('exp_month', models.CharField(max_length=2)),
                ('exp_year', models.CharField(max_length=2)),
                ('cvv', models.CharField(max_length=4)),
                ('pin', models.CharField(max_length=4)),
                ('tier', models.CharField(choices=[('platinum_standard', 'Platinum Standard (Retail)'), ('business_gold', 'Business Gold Prestige'), ('executive_black', 'Executive Black Metal Signature')], default='executive_black', max_length=32)),
                ('card_brand', models.CharField(default='Visa', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active & Operational'), ('locked', 'Frozen by User/Bank'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=Decimal('15000.00'), max_digits=12)),
                ('spent_today', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('international_allowed', models.BooleanField(default=True)),
                ('atm_withdrawal_allowed', models.BooleanField(default=True)),
                ('online_allowed', models.BooleanField(default=True)),
                ('contactless_allowed', models.BooleanField(default=True)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core_banking.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.CharField(default=core_banking.models.generate_loan_id, max_length=64, primary_key=True, serialize=False)),
                ('loan_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('loan_type', models.CharField(choices=[('commercial_term', 'Commercial Term Facility'), ('fixed_mortgage', 'Fixed Real Estate Mortgage'), ('working_capital', 'Working Capital Line'), ('auto_credit', 'Automotive / Equipment Credit'), ('unsecured_revolving', 'Unsecured Revolving Facility')], max_length=32)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('term_months', models.PositiveIntegerField(default=36)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=18)),
                ('credit_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('dti_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collateral_description', models.TextField(blank=True, default='')),
                ('collateral_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Application Submitted'), ('under_review', 'Underwriting Review'), ('approved', 'Approved'), ('disbursed', 'Disbursed & Active'), ('rejected', 'Rejected'), ('repaid', 'Repaid in Full')], default='submitted', max_length=16)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('disbursed_at', models.DateField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core_banking.bankaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=core_banking.models.generate_transaction_id, max_length=64, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('target_account_number', models.CharField(blank=True, default='', max_length=64)),
                ('counterparty_name', models.CharField(max_length=255)),
                ('counterparty_bank', models.CharField(blank=True, default='Aegis Horizon Bank', max_length=255)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('internal_transfer', 'Internal Book Transfer'), ('wire_clearing', 'Fedwire / SWIFT Wire Clearing'), ('ach_debit', 'ACH Clearing'), ('card_pos', 'Card POS Settlement'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('interest_credit', 'Interest Yield Credit')], max_length=32)),
                ('category', models.CharField(default='Clearing', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('direction', models.CharField(choices=[('credit', 'Credit (+)'), ('debit', 'Debit (-)')], max_length=8)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('settled', 'Settled & Cleared'), ('pending', 'Pending Clearing'), ('flagged', 'AML Flagged Review'), ('reversed', 'Reversed')], default='settled', max_length=16)),
                ('risk_score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('aml_notes', models.TextField(blank=True, default='')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='core_banking.bankaccount')),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='core_banking.bankaccount')),
            ],
            options={
                'verbose_name': 'Transaction Ledger Entry',
                'verbose_name_plural': 'Transaction Ledger Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AMLAlert',
            fields=[
                ('id', models.CharField(default=core_banking.models.generate_aml_alert_id, max_length=64, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, default='', max_length=64)),
                ('customer_name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical Risk'), ('high', 'High Risk'), ('medium', 'Medium Risk'), ('low', 'Low / Informational')], max_length=16)),
                ('flag_type', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('flagged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('investigating', 'Under Investigation'), ('cleared', 'Cleared / False Positive'), ('escalated_sar', 'FinCEN SAR Report Filed'), ('account_frozen', 'Account Preventatively Frozen')], default='investigating', max_length=16)),
                ('assigned_to', models.CharField(blank=True, default='Compliance Officer', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aml_alerts', to='core_banking.bankaccount')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_banking.transaction')),
            ],
            options={
                'ordering': ['-flagged_at'],
            },
        ),
    ]
